# Inherit StandardRB configuration
inherit_gem:
  standard: config/base.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# Project-specific overrides
Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

# RSpec-specific configurations
RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 25

RSpec/NestedGroups:
  Max: 5