name: Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches: [main, master]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Check Conventional Commits (PR only)
        if: github.event_name == 'pull_request'
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
          # Only check commits in this PR
          
      - name: Check Latest Commit (Push to main)
        if: github.event_name == 'push'
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
          commitDepth: 1