name: Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check Conventional Commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json