name: Release Please

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Create Release PR or Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

    - name: Run linters
      run: |
        bundle exec rubocop
        bundle exec standardrb --no-fix

    - name: Build gem
      run: gem build ruby-maat.gemspec

    - name: Configure RubyGems credentials
      run: |
        mkdir -p ~/.gem
        cat > ~/.gem/credentials << EOF
        ---
        :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
        EOF
        chmod 0600 ~/.gem/credentials

    - name: Publish to RubyGems
      run: |
        gem push ruby-maat-*.gem

    - name: Upload gem to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gem_file=$(ls ruby-maat-*.gem)
        gh release upload ${{ needs.release-please.outputs.tag_name }} "$gem_file"