name: Release Please

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write # Required to create releases and update changelog
      pull-requests: write # Required to create release PRs
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Create Release PR or Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: ruby
          config-file: .release-please-config.json

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      id-token: write # Mandatory for trusted publishing
      contents: write # Required for release
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Release gem
      uses: rubygems/release-gem@v1